version: "3.4"

networks:
  airports-network:
    driver: bridge

services:
  backend:
    container_name: airports-backend
    image: airports/backend
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_HTTPS_PORT: 5001
    ports:
      - 5001:5001
    networks:
      - airports-network
    volumes:
      - ~/.aspnet/https:/https:ro
  
  frontend:
    container_name: airports-frontend
    image: airports/frontend
    depends_on:
      - backend
    build:
      context: ./src/Frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
    networks:
      - airports-network